name: Crucible
version: 1.0.0
main: com.tt_tcs.crucible.CrucibleMain
api-version: '1.21'
author: TT_TCS
description: Drug manufacturing and chemical synthesis.

commands:
  crucible:
    description: Main command
    usage: /crucible <help|tolerance|settolerance>
    aliases: [c]
